package org.sde;

public enum Queries {
    INSERT,
    READ_PESSIMISTIC_ROW_LOCK,
    READ_PESSIMISTIC_CELL_LOCK,
    READ_OPTIMISTIC_ROW_LOCK,
    READ_OPTIMISTIC_CELL_LOCK,
    UPDATE_ROW_LOCK,
    UPDATE_CELL_LOCK,
}
